# Día 1 (tarde): Introducción a los modelos mixtos (cont.)

## Review: elements of statistical inference 

Most of us use statistics as a tool to summarize our data and obtain statistical inference. Let's review a few key parameters that may affect our results:

- Parameter estimates $\hat\beta$ 
  - Typically how we model our treatment effects 
- Variance estimates $\sigma^2$ 
  - Affect standard errors 
- Confidence intervals 
  - $CI_{\hat{\theta} \ 95\%} = \hat{\theta} \pm se(\hat{\theta}) \cdot t_{df, \ 1 - \frac{\alpha}{2}}$ 
- Hypothesis tests  
  - $CI_{\hat{\theta} \ 95\%} = \hat{\theta} \pm se(\hat{\theta}) \cdot t_{df, \ 1 - \frac{\alpha}{2}}$ 
  
### On p-values 


- The p value is the probability of observing the [t/F] statistic under the null hypothesis. 
- Often, we assume $\alpha = 0.05$, and reject $H_0$ if $p<\alpha$. 
- [ASA's statement on p-values](https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf) 
- [Scientists rise up against statistical significance](https://www.nature.com/articles/d41586-019-00857-9) 
  - [Discussion](https://statmodeling.stat.columbia.edu/2019/03/20/retire-statistical-significance-the-discussion/) 
  - Counterargument: [In defense of p-values](https://esajournals.onlinelibrary.wiley.com/doi/10.1890/13-0590.1) 
- Gelman "Let us have the serenity to embrace the variation that we cannot reduce, the courage to reduce the variation we cannot embrace, and the wisdom to distinguish one from the other." [[see talk](https://www.youtube.com/watch?v=KS3yPw91iC0&t=3252s)] 


## Estimation of variance components in mixed models

For any unknown parameter, there are multiple ways to estimate it. We call those the methods of estimation. 

### Maximum Likelihood Estimation (MLE)

**Maximum Likelihood Estimation** of variance components provides downward biased estimates for small data (most experimental data). 
$\ell_{ML}(\boldsymbol{\sigma; \boldsymbol{\beta}, \mathbf{y}}) = - (\frac{n}{2}) \log(2\pi)-(\frac{1}{2}) \log ( \vert \mathbf{V}(\boldsymbol\sigma) \vert ) - (\frac{1}{2}) (\mathbf{y}-\mathbf{X}\boldsymbol{\beta})^T[\mathbf{V}(\boldsymbol\sigma)]^{-1}(\mathbf{y}-\mathbf{X}\boldsymbol{\beta})$  

### Restricted Maximum Likelihood (REML)

**Restricted Maximum Likelihood** (REML) avoids MLE's downward bias under small data and is thus is the default in most mixed effects models. 

- In REML, the likelihood is maximized **after** accounting for the model’s fixed effects.  
- In REML, $\ell_{REML}(\boldsymbol{\sigma};\mathbf{y}) = - (\frac{n-p}{2}) \log (2\pi) - (\frac{1}{2}) \log ( \vert \mathbf{V}(\boldsymbol\sigma) \vert ) - (\frac{1}{2})log \left(  \vert \mathbf{X}^T[\mathbf{V}(\boldsymbol\sigma)]^{-1}\mathbf{X} \vert \right) - (\frac{1}{2})\mathbf{r}[\mathbf{V}(\boldsymbol\sigma)]^{-1}\mathbf{r}$, 
where $p = rank(\mathbf{X})$, $\mathbf{r} = \mathbf{y}-\mathbf{X}\hat{\boldsymbol{\beta}}_{ML}$.  
  - Start with initial values for $\boldsymbol{\sigma}$, $\tilde{\boldsymbol{\sigma}}$.  
  - Compute $\mathbf{G}(\tilde{\boldsymbol{\sigma}})$ and $\mathbf{R}(\tilde{\boldsymbol{\sigma}})$.  
  - Obtain $\boldsymbol{\beta}$ and $\mathbf{b}$.   
  - Update $\tilde{\boldsymbol{\sigma}}$.  
  - Repeat until convergence.  
- Variance components may be $<0$; in that case they are set to zero. 

### Method of moments (MoM)

**Method of moments** (MoM) is derived from ANOVA tables that include the expected mean squares. 

- Use actual sums of squares and expected mean squares (EMS) from ANOVA to clear for the different variance components. 
- e.g., $\tilde{\sigma}^2_{w} = \frac{SSw - SS_e}{c}$ (See table above). However, if $\tilde{\sigma}^2_{w} < 0$, $\hat{\sigma}^2_{w} = 0$. 

- Issues with variance estimates equal to zero 
  - Type I error inflation 
  - [Frey et al. (2024)](https://acsess.onlinelibrary.wiley.com/doi/10.1002/agj2.21570) 


## Degrees of freedom

Mixed models do not trace to the classical concept of degrees of freedom. In hierarchical models, rigidly counting parameters for degrees of freedom is conceptually problematic.

The independent pieces of information shift depending on group sizes and variance: a group-level coefficient modeled as a random effect does not consume exactly $1$ degree of freedom (as an unpooled fixed effect would), nor does it consume $0$ (as a completely pooled grand mean would). Instead, the effective degrees of freedom consumed by a set of random effects lies somewhere between $1$ and $J$ (where $J$ is the total number of groups).

The effective degrees of freedom depend on the magnitude of between-group versus within-group variance: if group variation is high, degrees of freedom approach the number of groups; if low, they approach the total sample size.

- Contrasts for balanced \& complete designs have straightforward calculation of degrees of freedom. 
- For unbalanced designs, incomplete blocks, missing data, and cases with more complex variance-covariance structure, the ANOVA shell does not give us exact degrees of freedom. 
- Downward bias of the variance of an estimable function, leading to: 
  - too narrow confidence intervals 
  - inflated type I error rates 
- Bias adjustment methods estimate the approximate degrees of freedom, which might be a non-integer number.  

**Satterthwaite approximation**  

- [Paper](https://www.jstor.org/stable/3002019?seq=1)  

Let $\frac{X^2_{num}/\nu_1}{X_2^\star/\nu^\star_2}$ be the ratio of interest, where $X_{num}^2 \sim \chi^2_{\nu_1}$ and $X_2^\star$ is a linear combination of chi-square random variables all independent of $X_{num}^2$, then $X_2^\star \sim$ approximately $\chi^2_{\nu^\star_2}$, where

$$\nu_2^\star \equiv \frac{(\sum_m c_m X_m^2)^2}{\sum_m\frac{(c_m X_m^2)}{df_m}}.$$

**Kenward-Roger approximation** 

- [Paper](https://www.jstor.org/stable/2533558?seq=1) 
- Based on REML 
- Focused on $(\mathbf{X}^T\mathbf{V}^{-1} \mathbf{X})^{-1}$ (the variance of $\hat{\boldsymbol\beta}$)
- Again, expept for variance-component-only LMMs with balanced data and their compound symmetry marginal model equivalents, the estimated covariance of $\beta \mathbf{K}$ will tend to be underestimated. 
- KR somewhat more conservative and reliable than Satterthwaite ([source](https://link.springer.com/article/10.1198/108571102726)). 
- Integrated in most statistical software. 

**R implementation** 

- `emmeans` uses Kenward-Roger by default. [[see vignette](https://cran.r-project.org/web/packages/emmeans/vignettes/sophisticated.html)] 
- Everything is more tricky in GLMMs (`df` is `Inf` in most applications). 


## Ejercicio

## Tarea para mañana:
 
Leer Dixon (2016). 

