--- 
title: "Modelos Lineales Mixtos Aplicados"
author: "Josefina Lacasa"
date: Octubre 2026 #"`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Bienvenidos!  
  

## Sobre el curso:  

- [Sobre mí](https://jlacasa.github.io/) 
- Sobre ustedes: 

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
# read.csv("../../students_STAT_720_C.csv") %>% 
#   ggplot(aes(x = degreeProgram))+
#   geom_bar(fill = "#B388EB")+
#   theme_bw()+
#   theme(panel.grid.minor = element_blank(),
#         panel.border = element_blank(),
#         axis.title.x = element_blank(), 
#         axis.text.x = element_text(angle = 50, vjust = 1, hjust=1))
```

- Presentaciones: 
  - Cuál es el tema de tu tesis? 
  - Qué esperás aprender?  

### Logística  

- [Página web](#)
- Idioma 
- Requerimientos de programación  
- Rough mindmap of the course (on whiteboard)  
- Notas.
- Asistencia  
- Examen final

## Objetivos de aprendizaje   

Al final de este curso, deberían saber: 
- Escribir el modelo estadístico que represente el proceso generador de datos, usando notación matemática. 
- Escribir la sección correspondiente al análisis estadístio en materiales y métodos. 
- Reconocer los beneficios y desventajas de distintos modelos.

## Notación utilizada en este curso  

- scalars: $y$, $\sigma$, $\beta_0$  
- vectors: $\mathbf{y} \equiv [y_1, y_2, ..., y_n]'$, $\boldsymbol{\beta} \equiv [\beta_1, \beta_2, ..., \beta_p]'$, $\boldsymbol{u}$  
- matrices: $\mathbf{X}$, $\Sigma$  
- probability distribution: $y \sim N(0, \sigma^2)$, $\mathbf{y} \sim N(\boldsymbol{0}, \sigma^2\mathbf{I})$.     


